# Generated by Django 4.2.2 on 2023-06-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Coming soon'), (2, 'Out of stock')], default=0),
        ),
    ]
