# Generated by Django 4.2.2 on 2023-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_image_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('percentil', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('date_close', models.DateTimeField()),
            ],
        ),
    ]
