# Generated by Django 4.2.2 on 2023-06-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Coming soon'), (2, 'Out of stock'), (7, 'Outlet'), (3, 'Presale'), (4, 'Awaiting stock'), (5, 'Hidden'), (6, 'Retired')], default=0),
        ),
    ]
