# Generated by Django 4.2.2 on 2023-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_discounts_discount_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_open',
            field=models.DateTimeField(),
        ),
    ]
