# Generated by Django 4.2.2 on 2023-06-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_discount_date_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='no_expiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_close',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_open',
            field=models.DateTimeField(blank=True),
        ),
    ]
