# Generated by Django 4.2.2 on 2023-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.FileField(blank=True, upload_to='img/products/variant'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='img/products/main'),
        ),
    ]
