# Generated by Django 4.2.2 on 2023-06-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productvariant_image_alter_productimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.discount'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
