# Generated by Django 4.2.2 on 2023-06-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productvariant_discount_productvariant_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
