# Generated by Django 4.2.2 on 2023-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_images_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Coming soon'), (2, 'Out of stock'), (7, 'Outlet'), (3, 'Presale'), (4, 'Awaiting stock'), (5, 'Hidden'), (6, 'Retired')], default=0),
        ),
    ]
