# Generated by Django 4.2.2 on 2023-06-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_available',
            new_name='in_inventory',
        ),
    ]
