# Generated by Django 4.2.2 on 2023-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_num_available_product_in_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_inventory',
            field=models.IntegerField(default=1),
        ),
    ]
