# Generated by Django 4.2.2 on 2023-06-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productvariant_in_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='percentil',
            new_name='discount',
        ),
    ]
