# Generated by Django 4.2.2 on 2023-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_percentil_discount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
