# Generated by Django 4.2.2 on 2023-06-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_discount_date_close_alter_discount_date_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='no_expiration',
        ),
    ]
