# Generated by Django 4.2.2 on 2023-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='regions',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
