# Generated by Django 4.2.2 on 2023-06-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_shipment_regions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipment',
            new_name='Shipping',
        ),
    ]
