# Generated by Django 4.2.2 on 2023-06-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_rename_shipment_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='zone_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='regions',
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shippingmethod')),
            ],
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shipping'),
        ),
    ]
