# Generated by Django 4.2.2 on 2023-06-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_shippingmethod_rename_zone_name_shipping_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='zone',
            new_name='shipping',
        ),
    ]
