# Generated by Django 4.2.2 on 2023-06-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_rename_zone_shippingmethod_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='shipping',
            new_name='zone',
        ),
    ]
