# Generated by Django 4.2.2 on 2023-06-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_rename_shipping_shippingmethod_zone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingZone',
        ),
    ]
