# Generated by Django 4.2.2 on 2023-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='zone',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ManyToManyField(to='shop.shippingzone'),
        ),
    ]
