# Generated by Django 4.2.2 on 2023-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_shippingmethod_zone_shippingmethod_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='max_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='min_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
