# Generated by Django 4.2.2 on 2023-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_rename_max_width_shippingrate_max_sizes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingrate',
            old_name='max_sizes',
            new_name='max_height',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='max_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
