# Generated by Django 4.2.2 on 2023-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_rename_max_sizes_shippingrate_max_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shippment',
            field=models.ManyToManyField(to='shop.shippingmethod'),
        ),
    ]
