# Generated by Django 4.2.2 on 2023-06-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_product_shippment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shippment',
            new_name='shipping',
        ),
    ]
