# Generated by Django 4.2.2 on 2023-06-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_rename_shippment_product_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping',
            new_name='shipping_method',
        ),
    ]
