# Generated by Django 4.2.2 on 2023-06-16 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_rename_shipping_product_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
