# Generated by Django 4.2.2 on 2023-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_method',
            field=models.ManyToManyField(blank=True, to='shop.shippingmethod'),
        ),
    ]
